### ISSUE TITLE
Problem with MongoDB cluster

### ISSUE THREAD

**Issue by mfeuermann** [VeliovGroup/Meteor-CRON-jobs#4]
Hello,

if im using connection string that contains Mongo Cluster
ex mongodb://developers:developers@10.0.1.250:27017,10.0.2.250:27017/myproject-dev?replicaSet=mongo_replication, there is problem in situation when primary MongoDB is down.

In normal case, Meteor reconnect app to other Cluster client.
If there is CronJob integrated, instance fall down..

I have this source code

```js
  const db = Meteor.users.rawDatabase();
  const cron = new CRONjob({db, resetOnInit: true, autoClear: true});

  const bound = Meteor.bindEnvironment((callback) => {
    callback();
  });


  const taskSyncTask = function (ready) {
    bound(() => {
      orderWorkerInstance.checkOrdersWaitingForRaynetSyn();
      ready();
    });
  };
```
With this error message: 
```log
20180607-13:23:28.557(2)? (STDERR) [object Object]
W20180607-13:23:28.559(2)? (STDERR)     at _debug (/Users/markus/.meteor/packages/ostrio_cron-jobs/.2.2.0.1aqpnqj.oetd++os+web.browser+web.cordova/npm/node_modules/josk/index.js:3:11)
W20180607-13:23:28.560(2)? (STDERR)     at collection.findOneAndUpdate (/Users/markus/.meteor/packages/ostrio_cron-jobs/.2.2.0.1aqpnqj.oetd++os+web.browser+web.cordova/npm/node_modules/josk/index.js:80:13)
W20180607-13:23:28.561(2)? (STDERR)     at handleCallback (/Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:120:56)
W20180607-13:23:28.561(2)? (STDERR)     at /Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/collection.js:2492:22
W20180607-13:23:28.562(2)? (STDERR)     at handleCallback (/Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:120:56)
W20180607-13:23:28.563(2)? (STDERR)     at /Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/db.js:314:20
W20180607-13:23:28.563(2)? (STDERR)     at /Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:469:18
W20180607-13:23:28.563(2)? (STDERR)     at _combinedTickCallback (internal/process/next_tick.js:131:7)
W20180607-13:23:28.564(2)? (STDERR)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
W20180607-13:23:28.565(2)? (STDERR) { MongoError: interrupted at shutdown
W20180607-13:23:28.566(2)? (STDERR)     at Function.MongoError.create (/Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
W20180607-13:23:28.567(2)? (STDERR)     at /Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:497:72
W20180607-13:23:28.567(2)? (STDERR)     at authenticateStragglers (/Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:443:16)
W20180607-13:23:28.567(2)? (STDERR)     at Connection.messageHandler (/Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:477:5)
W20180607-13:23:28.568(2)? (STDERR)     at Socket.<anonymous> (/Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:333:22)
W20180607-13:23:28.568(2)? (STDERR)     at emitOne (events.js:116:13)
W20180607-13:23:28.569(2)? (STDERR)     at Socket.emit (events.js:211:7)
W20180607-13:23:28.569(2)? (STDERR)     at addChunk (_stream_readable.js:263:12)
W20180607-13:23:28.569(2)? (STDERR)     at readableAddChunk (_stream_readable.js:250:11)
W20180607-13:23:28.570(2)? (STDERR)     at Socket.Readable.push (_stream_readable.js:208:10)
W20180607-13:23:28.570(2)? (STDERR)     at TCP.onread (net.js:594:20)
W20180607-13:23:28.570(2)? (STDERR)   name: 'MongoError',
W20180607-13:23:28.570(2)? (STDERR)   message: 'interrupted at shutdown',
W20180607-13:23:28.571(2)? (STDERR)   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1528370607 },
W20180607-13:23:28.571(2)? (STDERR)   ok: 0,
W20180607-13:23:28.571(2)? (STDERR)   errmsg: 'interrupted at shutdown',
W20180607-13:23:28.572(2)? (STDERR)   code: 11600,
W20180607-13:23:28.572(2)? (STDERR)   codeName: 'InterruptedAtShutdown',
W20180607-13:23:28.572(2)? (STDERR)   '$clusterTime': 
W20180607-13:23:28.573(2)? (STDERR)    { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1528370607 },
W20180607-13:23:28.573(2)? (STDERR)      signature: { hash: [Object], keyId: [Object] } } }
W20180607-13:23:28.573(2)? (STDERR) Uncaught Exception [josk] [General Error during runtime]: MongoError: interrupted at shutdown
W20180607-13:23:28.574(2)? (STDERR) Error: [josk] [General Error during runtime]: MongoError: interrupted at shutdown
W20180607-13:23:28.574(2)? (STDERR)     at collection.findOneAndUpdate (/Users/markus/.meteor/packages/ostrio_cron-jobs/.2.2.0.1aqpnqj.oetd++os+web.browser+web.cordova/npm/node_modules/josk/index.js:81:19)
W20180607-13:23:28.574(2)? (STDERR)     at handleCallback (/Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:120:56)
W20180607-13:23:28.575(2)? (STDERR)     at /Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/collection.js:2492:22
W20180607-13:23:28.575(2)? (STDERR)     at handleCallback (/Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:120:56)
W20180607-13:23:28.575(2)? (STDERR)     at /Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/db.js:314:20
W20180607-13:23:28.576(2)? (STDERR)     at /Users/markus/.meteor/packages/npm-mongo/.2.2.34.qztsqr.w4m9++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:469:18
W20180607-13:23:28.576(2)? (STDERR)     at _combinedTickCallback (internal/process/next_tick.js:131:7)
W20180607-13:23:28.576(2)? (STDERR)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
=> Exited with code: 1
W20180607-13:24:33.242(2)? (STDERR)           
W20180607-13:24:33.243(2)? (STDERR) /Users/markus/.meteor/packages/meteor-tool/.1.6.1.z27a56++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
W20180607-13:24:33.243(2)? (STDERR) 						throw(ex);
W20180607-13:24:33.244(2)? (STDERR) 						^
W20180607-13:24:33.244(2)? (STDERR) MongoError: connection 3 to 10.0.1.250:27017 timed out
```
Can you help me with this case ?
Thank you!

**Comment by dr-dimitru** [comment]
Hello @mfeuermann ,

Thank you for reporting this, we are investigating it

**Comment by mfeuermann** [comment]
Thank you very much! Thank you for your time!

**Comment by mfeuermann** [comment]
Hi im sorry, i solved this issue by using onError 
```js
  const errorVisible = function () {
    console.log('Ostrio CRON JOB - Unable to connect to MongoDB cluster... reconnecting!');
  };

const cron = new CRONjob({db, resetOnInit: true, autoClear: true, onError: errorVisible});
```
It seems to be ok and works fine!
Thanks

**Comment by dr-dimitru** [comment]
@mfeuermann so it was reconnecting itself, right? Only the exception output was confusing for you?

**Comment by mfeuermann** [comment]
App reconnecting OK, but if there was not implemented onError function, application fall down...
